CRITICAL - 2024-09-24 06:09:33 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Users.php(9): view('register')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:41:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:41:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:41:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:41:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:42:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:42:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:42:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:42:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:43:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:43:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:43:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:44:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:45:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:45:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:45:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:45:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:45:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:25:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:28:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:28:55 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:28:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:28:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:34:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-24 14:34:40 --> Error: Call to undefined function ser_value()
in APPPATH\Views\register.php on line 13.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 4 APPPATH\Controllers\Users.php(9): view('register')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:35:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-24 14:35:27 --> Error: Call to undefined function set_value()
in APPPATH\Views\register.php on line 13.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 4 APPPATH\Controllers\Users.php(9): view('register')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:37:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:37:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:37:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:37:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(23): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:38:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:38:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:38:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:38:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:38:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(23): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:41:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:03:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:03:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:03:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:17:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:18:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:18:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:18:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:26:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:26:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:26:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:26:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:26:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:26:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:28:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:28:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:28:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 16:03:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 16:52:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 16:53:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 16:53:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 16:53:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(26): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 16:54:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 16:55:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 16:55:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 16:55:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(26): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 17:23:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:26:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 17:26:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 17:26:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(26): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 17:30:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 17:30:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 17:30:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(26): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 17:31:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:32:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:32:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:32:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 17:32:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\project\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 17:32:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-09-24 17:32:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'admin\', \'$2y$10$q.J35X7LkoRd5.uoenIsKuDa5l2qDuYf5c8QM2FGblbEkM0ug.aAi\', \'abner\', \'admin@codigosdeprogramacion.com\', 0, \'e8c669f6551d390ec41e8ae54f8951a2c3cb1597\', \'2024-09-24 17:32:47\', \'2024-09-24 17:32:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'admin\', \'$2y$10$q.J35X7LkoRd5.uoenIsKuDa5l2qDuYf5c8QM2FGblbEkM0ug.aAi\', \'abner\', \'admin@codigosdeprogramacion.com\', 0, \'e8c669f6551d390ec41e8ae54f8951a2c3cb1597\', \'2024-09-24 17:32:47\', \'2024-09-24 17:32:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-09-24 17:32:47 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'admin\', \'$2y$10$q.J35X7LkoRd5.uoenIsKuDa5l2qDuYf5c8QM2FGblbEkM0ug.aAi\', \'abner\', \'admin@codigosdeprogramacion.com\', 0, \'e8c669f6551d390ec41e8ae54f8951a2c3cb1597\', \'2024-09-24 17:32:47\', \'2024-09-24 17:32:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'admin\', \'$2y$10$q.J35X7LkoRd5.uoenIsKuDa5l2qDuYf5c8QM2FGblbEkM0ug.aAi\', \'abner\', \'admin@codigosdeprogramacion.com\', 0, \'e8c669f6551d390ec41e8ae54f8951a2c3cb1597\', \'2024-09-24 17:32:47\', \'2024-09-24 17:32:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'admin\', \'$2y$10$q.J35X7LkoRd5.uoenIsKuDa5l2qDuYf5c8QM2FGblbEkM0ug.aAi\', \'abner\', \'admin@codigosdeprogramacion.com\', 0, \'e8c669f6551d390ec41e8ae54f8951a2c3cb1597\', \'2024-09-24 17:32:47\', \'2024-09-24 17:32:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 17:34:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:35:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:35:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:35:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:35:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:36:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 17:36:30 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\project\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\project\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\project\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 17:36:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-09-24 17:36:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$6WCxJwrTrwx7Ir3OiE6AgO2DZ2Vwd6SmRhoima4eKF6ftMdXLwuz6\', \'prueba\', \'correo@codigosdeprogramacion.com\', 0, \'000b5611f1d389d2cba522468d1bc6bfd9d60dde\', \'2024-09-24 17:36:30\', \'2024-09-24 17:36:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$6WCxJwrTrwx7Ir3OiE6AgO2DZ2Vwd6SmRhoima4eKF6ftMdXLwuz6\', \'prueba\', \'correo@codigosdeprogramacion.com\', 0, \'000b5611f1d389d2cba522468d1bc6bfd9d60dde\', \'2024-09-24 17:36:30\', \'2024-09-24 17:36:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-09-24 17:36:30 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$6WCxJwrTrwx7Ir3OiE6AgO2DZ2Vwd6SmRhoima4eKF6ftMdXLwuz6\', \'prueba\', \'correo@codigosdeprogramacion.com\', 0, \'000b5611f1d389d2cba522468d1bc6bfd9d60dde\', \'2024-09-24 17:36:30\', \'2024-09-24 17:36:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$6WCxJwrTrwx7Ir3OiE6AgO2DZ2Vwd6SmRhoima4eKF6ftMdXLwuz6\', \'prueba\', \'correo@codigosdeprogramacion.com\', 0, \'000b5611f1d389d2cba522468d1bc6bfd9d60dde\', \'2024-09-24 17:36:30\', \'2024-09-24 17:36:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (\'Admin\', \'$2y$10$6WCxJwrTrwx7Ir3OiE6AgO2DZ2Vwd6SmRhoima4eKF6ftMdXLwuz6\', \'prueba\', \'correo@codigosdeprogramacion.com\', 0, \'000b5611f1d389d2cba522468d1bc6bfd9d60dde\', \'2024-09-24 17:36:30\', \'2024-09-24 17:36:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user`, `password`, `name`, `email`, `active`, `activation_token`, `created_at`, `updated_at`) VALUES (:user:, :password:, :name:, :email:, :active:, :activation_token:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Users.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 17:46:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:47:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 17:52:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
